### PR TITLE
[Hotfix] Update the field to the one provided by the new python-bugzilla

### PR DESCRIPTION
**Pull request by puiterwijk**

### CODE REVIEW

**Comment by pypingou** [comment]
The change itself looks fine but the commit message is not very descriptive or informative, might be worth rewording it.

**Comment by abadger** [comment]
:+1:

**Comment by abadger** [comment]
Thanks puiterwijk!

**Comment by pypingou** [comment]
Should it be merge now?

**Comment by pypingou** [comment]
@puiterwijk ?

**Pull request merged**
